apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-db
  labels:
    app: {{ .Values.app.name }}-db
spec:
  type: NodePort
  ports:
    - port: {{ .Values.db.port }}
  selector:
    app: {{ .Values.app.name }}-db