apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app.name }}-persistent-volume
  labels:
    type: local
    app: {{ .Values.app.name }}-db
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/zimahaba/data"